### ISSUE TITLE
Hot code reloads in case of `defonce`

### ISSUE THREAD

**Issue by hauleth** [hauleth/defconst#3]
Currently hot code reloads will not affect `defonce` defined values. So the question is how it should be handled. I see few potential approaches there:

- Generate random value at compile time, that will be used as a part of the key
- Use `@on_load` hook to cleanup `persistent_term` from any previously set value
- Provide cleanup function that will allow manual cleanup of cache and force users to handle that on their own

Each of these approaches have pros and cons, but I am not sure what would be the proper way to handle it.

**Comment by mayel** [comment]
I guess using a random key on each compile would avoid garbage collection of persistent term at the cost of storing both the old term and new one (until next time the app is restarted)?

**Comment by hauleth** [comment]
Pretty much. It would make cleanup of old data much harder.

**Comment by hauleth** [comment]
Closed by https://github.com/hauleth/defconst/commit/a3eea4164b4f05b2b7ca8b0ad40e45dfb8f4b611 as it will use hash created from the body of the function to prevent recomputation when not needed.
